apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-sg-chart.fullname" . }}
  labels:
    {{- include "nginx-sg-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port1.containerPort }}
      protocol: TCP
      name: {{ .Values.port1.name }}
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.port2.containerPort }}
      protocol: TCP
      name: {{ .Values.port2.name }}
  selector:
    {{- include "nginx-sg-chart.selectorLabels" . | nindent 4 }}
