apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx-sg-chart.fullname" . }}
  labels:
    {{- include "nginx-sg-chart.labels" . | nindent 4 }}
spec:
  serviceName: "nginxchart-nginx-sg-chart"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  #podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "nginx-sg-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-sg-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name:  {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        volumeMounts:
        - name: www
          mountPath: {{ .Values.volumeMounts.mountPath }}
        ports:
          {{- range .Values.ports1 }} 
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
          protocol: TCP
          {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
    {{- range .Values.volumeClaimTemplates }}
      storageClassName: {{ .spec.storageClassName | quote }}
      
      accessModes: {{ .spec.accessModes}}
      resources:
        requests:
          storage: 100Mi
    {{- end }}