apiVersion: v1
kind: Service
metadata: 
  name: pv-service
  labels:
    app: nginx
spec: 
  type: NodePort
  selector:
    app: nginx
  ports: 
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31234