apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service
  labels:
    app: myapp

spec:
  type: NodePort
  selector: 
    app: myapp
  ports:
  - name: http
    port: 80 #service port
    targetPort: 80 # Container Port
    nodePort: 31231  # NodePort